CREATE TABLE [stg].[Boeking] (
    [ID]                            BIGINT             NULL,
    [Boekdatum]                     DATETIMEOFFSET (7) NULL,
    [SchadeRelatie]                 DECIMAL (38, 18)   NULL,
    [KostenRelatie]                 DECIMAL (38, 18)   NULL,
    [TotaalRelatie]                 DECIMAL (38, 18)   NULL,
    [NettoMaatschappij]             DECIMAL (38, 18)   NULL,
    [NettoKantoor]                  DECIMAL (38, 18)   NULL,
    [Omschrijving]                  NVARCHAR (MAX)     NULL,
    [Referentie]                    NVARCHAR (MAX)     NULL,
    [BetalingsReferentie]           NVARCHAR (MAX)     NULL,
    [CourtageType]                  NVARCHAR (MAX)     NULL,
    [IsExcasso]                     NVARCHAR (MAX)     NULL,
    [IsGefiatteerd]                 BIT                NULL,
    [IsKlaarVoorANVA]               BIT                NULL,
    [IsSysteemBoeking]              BIT                NULL,
    [IsANVACorrectie]               BIT                NULL,
    [IsBEB_EnGeconverteerd]         BIT                NULL,
    [ANVA_Transactienr]             BIGINT             NULL,
    [ANVA_Geboekt]                  BIT                NULL,
    [ANVA_Factuurnummer]            NVARCHAR (MAX)     NULL,
    [IsGeconverteerd]               BIT                NULL,
    [isHerstelBoeking]              BIT                NULL,
    [IsVerwijderd]                  BIT                NULL,
    [Boeking_HerstelBoeking]        BIGINT             NULL,
    [Boeking_Dekkingsregel]         BIGINT             NULL,
    [Boeking_BetalingOntvangstCode] BIGINT             NULL,
    [Boeking_DossierBetrokkene]     BIGINT             NULL,
    [Boeking_Account_Behandelaar]   BIGINT             NULL,
    [Boeking_Account_Fiatteur]      BIGINT             NULL,
    [Gebeurtenis_Boeking]           BIGINT             NULL
);

