CREATE TABLE [stg].[Correspondentietaak] (
    [ID]                                  BIGINT             NULL,
    [createdDate]                         DATETIMEOFFSET (7) NULL,
    [owner]                               BIGINT             NULL,
    [HeeftNieuwDossier]                   BIT                NULL,
    [TaskId]                              BIGINT             NULL,
    [Description]                         NVARCHAR (MAX)     NULL,
    [Reference]                           NVARCHAR (MAX)     NULL,
    [Timestamp]                           DATETIMEOFFSET (7) NULL,
    [StartDate]                           DATETIMEOFFSET (7) NULL,
    [DueDate]                             DATETIMEOFFSET (7) NULL,
    [DoneDate]                            DATETIMEOFFSET (7) NULL,
    [DoneBy]                              NVARCHAR (MAX)     NULL,
    [Status]                              NVARCHAR (MAX)     NULL,
    [Priority]                            NVARCHAR (MAX)     NULL,
    [LockStatus]                          NVARCHAR (MAX)     NULL,
    [Deeplink]                            NVARCHAR (MAX)     NULL,
    [HeeftBijlage]                        BIT                NULL,
    [DueStatus]                           NVARCHAR (MAX)     NULL,
    [HasOwner]                            BIT                NULL,
    [CorrespondentieTaak]                 BIT                NULL,
    [MeldingTaak]                         BIT                NULL,
    [DossierTaak]                         BIT                NULL,
    [AdministratieveTaak]                 BIT                NULL,
    [AdhocTask]                           BIT                NULL,
    [AlertTask]                           BIT                NULL,
    [CorrespondentieTaak_Correspondentie] BIGINT             NULL,
    [CorrespondentieTaak_DDiDocument]     BIGINT             NULL,
    [Task_ProcessInstance]                BIGINT             NULL,
    [Task_TaskTemplate]                   BIGINT             NULL,
    [Correspondentie_Task]                BIGINT             NULL,
    [Task_Account_Select]                 BIGINT             NULL,
    [Task_Dossier]                        BIGINT             NULL,
    [Task_Melding]                        BIGINT             NULL
);

