CREATE TABLE [stg].[DekkingDetail] (
    [ID]                        BIGINT           NULL,
    [Relatienr]                 DECIMAL (38, 18) NULL,
    [Volgnr]                    NVARCHAR (MAX)   NULL,
    [VolgnrSub]                 DECIMAL (38, 18) NULL,
    [DekVolgnr]                 DECIMAL (38, 18) NULL,
    [DekCode]                   NVARCHAR (MAX)   NULL,
    [VerzekerdeSom]             DECIMAL (38, 18) NULL,
    [BrutoPremie]               DECIMAL (38, 18) NULL,
    [BMBedrag]                  DECIMAL (38, 18) NULL,
    [Toeslagbedrag]             DECIMAL (38, 18) NULL,
    [Assbel]                    DECIMAL (38, 18) NULL,
    [NettoPremie]               DECIMAL (38, 18) NULL,
    [Incassobedrag]             DECIMAL (38, 18) NULL,
    [Bouwjaar]                  BIGINT           NULL,
    [WAbedrag]                  DECIMAL (38, 18) NULL,
    [EigenRisico]               DECIMAL (38, 18) NULL,
    [EROmschrijving_10044]      NVARCHAR (MAX)   NULL,
    [Index_10056]               NVARCHAR (MAX)   NULL,
    [Indexcijfer]               BIGINT           NULL,
    [Bestemming_10081]          NVARCHAR (MAX)   NULL,
    [Bouwaard_10082]            NVARCHAR (MAX)   NULL,
    [Premiepercentage]          DECIMAL (38, 18) NULL,
    [Premiepromillage]          DECIMAL (38, 18) NULL,
    [Dekkingsgebied_10246]      NVARCHAR (MAX)   NULL,
    [CollToeslagbedrag]         DECIMAL (38, 18) NULL,
    [CollToeslagperc]           DECIMAL (38, 18) NULL,
    [CollToeslagTot]            DECIMAL (38, 18) NULL,
    [Merk]                      NVARCHAR (MAX)   NULL,
    [Model]                     NVARCHAR (MAX)   NULL,
    [ToeslagbedragTot]          DECIMAL (38, 18) NULL,
    [EinddatumDekking]          NVARCHAR (MAX)   NULL,
    [Chassisnummer]             NVARCHAR (MAX)   NULL,
    [RisicoadresStraat]         NVARCHAR (MAX)   NULL,
    [RisicoHuisnr]              BIGINT           NULL,
    [RisicoHuisnrTv]            NVARCHAR (MAX)   NULL,
    [RisicoadresPlaats]         NVARCHAR (MAX)   NULL,
    [Objectnummer]              NVARCHAR (MAX)   NULL,
    [SrtVoertuig_81070]         NVARCHAR (MAX)   NULL,
    [OmschrijvingObject]        NVARCHAR (MAX)   NULL,
    [Nummer]                    NVARCHAR (MAX)   NULL,
    [DatumWijziging]            NVARCHAR (MAX)   NULL,
    [KentekenObject]            NVARCHAR (MAX)   NULL,
    [OmschrijvingRisico]        NVARCHAR (MAX)   NULL,
    [Versie]                    BIGINT           NULL,
    [VersieDatum]               NVARCHAR (MAX)   NULL,
    [DekkingDetail_PolisDetail] BIGINT           NULL,
    [DekkingDetail_DekkingCode] BIGINT           NULL
);

