CREATE TABLE [stg].[DossierBetrokkene] (
    [ID]                                        BIGINT             NULL,
    [Voornaam]                                  NVARCHAR (MAX)     NULL,
    [Initialen]                                 NVARCHAR (MAX)     NULL,
    [Achternaam]                                NVARCHAR (MAX)     NULL,
    [Tussenvoegsel]                             NVARCHAR (MAX)     NULL,
    [Aanhef]                                    NVARCHAR (MAX)     NULL,
    [Geboortedatum]                             DATETIMEOFFSET (7) NULL,
    [Adres]                                     NVARCHAR (MAX)     NULL,
    [Huisnummer]                                NVARCHAR (MAX)     NULL,
    [HuisnummerToevoeging]                      NVARCHAR (MAX)     NULL,
    [Plaats]                                    NVARCHAR (MAX)     NULL,
    [IsBuitenland]                              BIT                NULL,
    [Postcode]                                  NVARCHAR (MAX)     NULL,
    [PostcodeBuitenland]                        NVARCHAR (MAX)     NULL,
    [LandBuitenland]                            NVARCHAR (MAX)     NULL,
    [AdresIsCorrespondentieAdres]               BIT                NULL,
    [CorrespondentieAdres]                      NVARCHAR (MAX)     NULL,
    [CorrespondentieHuisnummer]                 NVARCHAR (MAX)     NULL,
    [CorrespondentieHuisnummerToevoeging]       NVARCHAR (MAX)     NULL,
    [CorrespondentiePlaats]                     NVARCHAR (MAX)     NULL,
    [CorrespondentiePostcode]                   NVARCHAR (MAX)     NULL,
    [CorrespondentiePostcodeBuitenland]         NVARCHAR (MAX)     NULL,
    [CorrespondentieLandBuitenland]             NVARCHAR (MAX)     NULL,
    [Email]                                     NVARCHAR (MAX)     NULL,
    [Telefoonnummer]                            NVARCHAR (MAX)     NULL,
    [Bankrekeningnummer]                        NVARCHAR (MAX)     NULL,
    [ANVA_BetrokkeneSchade_PK]                  NVARCHAR (MAX)     NULL,
    [Volgnummer]                                BIGINT             NULL,
    [ANVA_Geboekt]                              BIT                NULL,
    [IsEersteLijnsBetrokkene]                   BIT                NULL,
    [VolledigeNaam]                             NVARCHAR (MAX)     NULL,
    [VolledigeNaamEnHoortBij]                   NVARCHAR (MAX)     NULL,
    [IsVasteBetrokkene]                         BIT                NULL,
    [Kenteken]                                  NVARCHAR (MAX)     NULL,
    [Referentie]                                NVARCHAR (MAX)     NULL,
    [Omschrijving]                              NVARCHAR (MAX)     NULL,
    [Letsel]                                    NVARCHAR (MAX)     NULL,
    [IsTegenpartij]                             BIT                NULL,
    [IsBeschikbaarVoorBoekingen]                BIT                NULL,
    [Contactpersoon]                            NVARCHAR (MAX)     NULL,
    [IsRechtspersoon]                           BIT                NULL,
    [Postbanknummer]                            NVARCHAR (MAX)     NULL,
    [PK_Conversie]                              NVARCHAR (MAX)     NULL,
    [Volgnummer_Conversie]                      BIGINT             NULL,
    [VasteBetrokkeneID]                         NVARCHAR (MAX)     NULL,
    [Personeelsnummer]                          NVARCHAR (MAX)     NULL,
    [BuitenlandsKenteken]                       BIT                NULL,
    [DossierBetrokkene_DossierBetrokkene]       BIGINT             NULL,
    [DossierBetrokkene_MeldingBetrokkene]       BIGINT             NULL,
    [DossierBetrokkene_BetrokkeneType]          BIGINT             NULL,
    [DossierBetrokkene_TegenpartijType]         BIGINT             NULL,
    [DossierBetrokkene_HoofdDossier]            BIGINT             NULL,
    [DossierBetrokkene_HerverzekeringsContract] BIGINT             NULL,
    [DossierBetrokkene_VasteBetrokkene]         BIGINT             NULL
);

