CREATE TABLE [stg].[HoofdDossier] (
    [ID]                                   BIGINT             NULL,
    [DossierDatum]                         DATETIMEOFFSET (7) NULL,
    [DossierNummer]                        NVARCHAR (MAX)     NULL,
    [Melddatum]                            DATETIMEOFFSET (7) NULL,
    [Schadedatum]                          DATETIMEOFFSET (7) NULL,
    [Schadetijd]                           NVARCHAR (MAX)     NULL,
    [IsSchadePeriode]                      BIT                NULL,
    [SchadeperiodeStart]                   DATETIMEOFFSET (7) NULL,
    [SchadeperiodeEind]                    DATETIMEOFFSET (7) NULL,
    [Schuldschade]                         BIT                NULL,
    [Terugval]                             BIT                NULL,
    [IsLetsel]                             BIT                NULL,
    [Tekenjaar]                            BIGINT             NULL,
    [OmschrijvingSchadeoorzaak]            NVARCHAR (MAX)     NULL,
    [ANVA_SchadeKey]                       NVARCHAR (MAX)     NULL,
    [ANVA_Schadenummer]                    NVARCHAR (MAX)     NULL,
    [ANVA_IsVerstuurd]                     BIT                NULL,
    [DossierVolgnummer]                    BIGINT             NULL,
    [AfsluitDatum]                         DATETIMEOFFSET (7) NULL,
    [AfsluitStatus]                        NVARCHAR (MAX)     NULL,
    [IsNieuw]                              BIT                NULL,
    [EigenBehoud]                          DECIMAL (38, 18)   NULL,
    [IsGeconverteerd]                      BIT                NULL,
    [HeeftEigenRisico]                     BIT                NULL,
    [EigenRisico]                          DECIMAL (38, 18)   NULL,
    [LaatsteSubdossierNummer]              BIGINT             NULL,
    [AutoNumber]                           BIGINT             NULL,
    [IsCommunicatieDossier]                BIT                NULL,
    [ANVA_BEB_Bedrag]                      DECIMAL (38, 18)   NULL,
    [SkipBEBControle]                      BIT                NULL,
    [InloopRisico]                         NVARCHAR (MAX)     NULL,
    [isBEBCorrectie]                       BIT                NULL,
    [HoofdDossier_Melding]                 BIGINT             NULL,
    [HoofdDossier_Klant]                   BIGINT             NULL,
    [HoofdDossier_Relatie]                 BIGINT             NULL,
    [HoofdDossier_Collectiviteit]          BIGINT             NULL,
    [HoofdDossier_Polis]                   BIGINT             NULL,
    [HoofdDossier_Schadelocatie]           BIGINT             NULL,
    [HoofdDossier_Schadesoort]             BIGINT             NULL,
    [HoofdDossier_HerverzekeringsContract] BIGINT             NULL,
    [HoofdDossier_Herverzekering_Sub]      BIGINT             NULL,
    [HoofdDossier_Hoofdbranche]            BIGINT             NULL,
    [HoofdDossier_EigenRisicoDepot]        BIGINT             NULL,
    [HoofdDossier_Organisatie]             BIGINT             NULL
);

