CREATE TABLE [stg].[MeldingProces] (
    [ID]                                       BIGINT             NULL,
    [owner]                                    BIGINT             NULL,
    [IsHeropenen]                              BIT                NULL,
    [IsIngediendBijVGA]                        BIT                NULL,
    [IsGeannuleerd]                            BIT                NULL,
    [IsGesloten]                               BIT                NULL,
    [IsAangemaaktVanuitDossier]                BIT                NULL,
    [IsInBehandelingVGA]                       BIT                NULL,
    [HeeftDossiers]                            BIT                NULL,
    [ProcessInstanceId]                        BIGINT             NULL,
    [StartDate]                                DATETIMEOFFSET (7) NULL,
    [EndDate]                                  DATETIMEOFFSET (7) NULL,
    [TimeEnteredState]                         DATETIMEOFFSET (7) NULL,
    [DontStartBefore]                          DATETIMEOFFSET (7) NULL,
    [IsQueued]                                 BIT                NULL,
    [TryCount]                                 BIGINT             NULL,
    [OverrideNumberOfRetries]                  BIGINT             NULL,
    [ProcessResult]                            BIT                NULL,
    [IsLocalProcess]                           BIT                NULL,
    [Status]                                   NVARCHAR (MAX)     NULL,
    [ReferenceCase]                            NVARCHAR (MAX)     NULL,
    [ReferenceParty]                           NVARCHAR (MAX)     NULL,
    [ReferenceOther]                           NVARCHAR (MAX)     NULL,
    [HasArchivedTasks]                         BIT                NULL,
    [Melding_MeldingProces]                    BIGINT             NULL,
    [ProcessInstance_ProcessDefinitionVersion] BIGINT             NULL,
    [ProcessInstance_State_Current]            BIGINT             NULL,
    [ProcessInstance_ParentProcessInstance]    BIGINT             NULL,
    [ProcessInstance_Account_Owner]            BIGINT             NULL
);

