CREATE TABLE [stg].[PolisDetail] (
    [ID]                                  BIGINT           NULL,
    [Relatienr]                           DECIMAL (38, 18) NULL,
    [Volgnr]                              NVARCHAR (MAX)   NULL,
    [VolgnrSub]                           DECIMAL (38, 18) NULL,
    [PakketSW]                            NVARCHAR (MAX)   NULL,
    [Polisnr]                             NVARCHAR (MAX)   NULL,
    [Kenteken]                            NVARCHAR (MAX)   NULL,
    [Hoofdbranche_10141]                  NVARCHAR (MAX)   NULL,
    [Branche_10142]                       NVARCHAR (MAX)   NULL,
    [Mijcode_10001]                       NVARCHAR (MAX)   NULL,
    [Mijsoort]                            NVARCHAR (MAX)   NULL,
    [Collnr_10095]                        NVARCHAR (MAX)   NULL,
    [Producent_10015]                     NVARCHAR (MAX)   NULL,
    [Agent_10027]                         NVARCHAR (MAX)   NULL,
    [Incassowijze_10016]                  NVARCHAR (MAX)   NULL,
    [Ingangsdatum]                        DECIMAL (38, 18) NULL,
    [Termijn]                             DECIMAL (38, 18) NULL,
    [PremieVervaldatum]                   DECIMAL (38, 18) NULL,
    [HoofdVervaldatum]                    DECIMAL (38, 18) NULL,
    [Looptijd]                            DECIMAL (38, 18) NULL,
    [ContractsVervaldatum]                NVARCHAR (MAX)   NULL,
    [Wijzigingsdatum]                     NVARCHAR (MAX)   NULL,
    [Status]                              NVARCHAR (MAX)   NULL,
    [SchadeAanwezig]                      DECIMAL (38, 18) NULL,
    [Gewicht]                             DECIMAL (38, 18) NULL,
    [VerzekerdeSom]                       DECIMAL (38, 18) NULL,
    [Catwaarde]                           DECIMAL (38, 18) NULL,
    [SvJaren]                             DECIMAL (38, 18) NULL,
    [BMPerc]                              DECIMAL (38, 18) NULL,
    [Brutopremie]                         DECIMAL (38, 18) NULL,
    [Nettopremie]                         DECIMAL (38, 18) NULL,
    [Incassobedrag]                       DECIMAL (38, 18) NULL,
    [Toeslagbedrag]                       DECIMAL (38, 18) NULL,
    [BMBedrag]                            DECIMAL (38, 18) NULL,
    [EigenRisico]                         DECIMAL (38, 18) NULL,
    [Voorwaarden1_10698]                  NVARCHAR (MAX)   NULL,
    [Voorwaarden2_10698]                  NVARCHAR (MAX)   NULL,
    [Voorwaarden3_10698]                  NVARCHAR (MAX)   NULL,
    [Voorwaarden4_10698]                  NVARCHAR (MAX)   NULL,
    [Voorwaarden5_10698]                  NVARCHAR (MAX)   NULL,
    [Voorwaarden1]                        NVARCHAR (MAX)   NULL,
    [Voorwaarden2]                        NVARCHAR (MAX)   NULL,
    [Voorwaarden3]                        NVARCHAR (MAX)   NULL,
    [Voorwaarden4]                        NVARCHAR (MAX)   NULL,
    [Voorwaarden5]                        NVARCHAR (MAX)   NULL,
    [Clausule1_10703]                     NVARCHAR (MAX)   NULL,
    [Clausule2_10703]                     NVARCHAR (MAX)   NULL,
    [Clausule3_10703]                     NVARCHAR (MAX)   NULL,
    [Clausule4_10703]                     NVARCHAR (MAX)   NULL,
    [Clausule5_10703]                     NVARCHAR (MAX)   NULL,
    [Clausule1]                           NVARCHAR (MAX)   NULL,
    [Clausule2]                           NVARCHAR (MAX)   NULL,
    [Clausule3]                           NVARCHAR (MAX)   NULL,
    [Clausule4]                           NVARCHAR (MAX)   NULL,
    [Clausule5]                           NVARCHAR (MAX)   NULL,
    [Omschrijving]                        NVARCHAR (MAX)   NULL,
    [Parknr]                              NVARCHAR (MAX)   NULL,
    [Versie]                              DECIMAL (38, 18) NULL,
    [VersieDatum]                         NVARCHAR (MAX)   NULL,
    [Maatschappij]                        NVARCHAR (MAX)   NULL,
    [Gebruik_10260]                       NVARCHAR (MAX)   NULL,
    [Hoofdbranche]                        NVARCHAR (MAX)   NULL,
    [Branche]                             NVARCHAR (MAX)   NULL,
    [Naam]                                NVARCHAR (MAX)   NULL,
    [Voorletters]                         NVARCHAR (MAX)   NULL,
    [Voorvoegsels]                        NVARCHAR (MAX)   NULL,
    [BTW_10102]                           NVARCHAR (MAX)   NULL,
    [BTW_verrekenbaar]                    NVARCHAR (MAX)   NULL,
    [Wijzigingsreden]                     NVARCHAR (MAX)   NULL,
    [Wijz_omschrijving]                   NVARCHAR (MAX)   NULL,
    [Risico_Straat]                       NVARCHAR (MAX)   NULL,
    [Risico_Huisnr]                       NVARCHAR (MAX)   NULL,
    [Risico_HuisnrTV]                     NVARCHAR (MAX)   NULL,
    [Risico_Postcode]                     NVARCHAR (MAX)   NULL,
    [Risico_Plaats]                       NVARCHAR (MAX)   NULL,
    [ZijnPolisbladenAlEerderOpgehaald]    BIT              NULL,
    [Routecode]                           NVARCHAR (MAX)   NULL,
    [PolisDetail_PolisStamdata]           BIGINT           NULL,
    [Polis_PolisDetail]                   BIGINT           NULL,
    [EigenRisicoDepot_PolisDetail]        BIGINT           NULL,
    [HerverzekeringsContract_PolisDetail] BIGINT           NULL
);

